apiVersion: apps/v1
kind: Deployment
metadata:
  name: appcat-apiserver
  namespace: appcat
  labels:
    api: appcat
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: appcat
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: appcat
        apiserver: "true"
    spec:
      containers:
        - name: apiserver
          image: "ghcr.io/vshn/appcat:v0.0.1" #patched
          volumeMounts:
            - name: apiserver-certs
              mountPath: /apiserver.local.config/certificates
              readOnly: true
          args:
            - "apiserver"
            - "--secure-port=9443"
            - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
            - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
            - "--audit-log-path=-"
            - "--enable-priority-and-fairness=false" # k8s 1.29+ only
            - "--disable-admission-plugins=ValidatingAdmissionPolicy" # k8s 1.30+ only
            - "--audit-log-maxage=0"
            - "--audit-log-maxbackup=0"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 200Mi
      serviceAccountName: appcat-apiserver
      volumes:
        - name: apiserver-certs
          secret:
            secretName: appcat
