apiVersion: v1
kind: Service
metadata:
  name: appcat
  namespace: appcat
  labels:
    api: appcat
    apiserver: "true"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    api: appcat
    apiserver: "true"
